version: '3.8'
services:
  nest-xample:
    container_name: ${APPLICATION_NAME}_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
 
    environment:
      - APPLICATION_NAME=${APPLICATION_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_HOST=${SERVICE_HOST}